import type { Locale } from './i18n-data';
import { CUSTOMER_GUIDES, CUSTOMER_SLUGS, type ProductSlug } from './customer-content';
import { SERVICE_INFO } from './service-data';
import './customer-pages.css';

type Copy = Record<Locale, string>;
const t = (ja: string, en: string, zh: string): Copy => ({ ja, en, 'zh-CN': zh });
const LABELS = {
  ja: { index:'顧客向けドキュメント', intro:'「何を用意し、どのボタンを押し、何が返るか」を16サービス別に説明します。基盤の契約や運営者用の設定は必要ありません。', home:'サービス一覧', dashboard:'全体ダッシュボード', explain:'製品説明', open:'操作画面', steps:'画面での操作手順', before:'あなたが準備するもの', sample:'動作を確かめる例', api:'管理API入口', after:'使う前に確認', note:'これは利用例です。$BASE_URL、$SESSION_TOKEN、発行URLなどの仮値は実際の値へ置換してください。セッショントークン・APIキーを公開ページやGitHubに記載しないでください。', limitations:'できないこと・制約', compare:'機能比較と公式資料', back:'全ドキュメント', formsTitle:'Formsはフォーム画面ではなく、投稿の送信先です', formsDetail:'PicoSvcで「フォーム」を作ると投稿用URLが返ります。下のHTMLはご自身のサイトに置き、actionのURLを発行されたendpointに置き換えます。投稿は管理画面に保存されます。HTML・CSSの見た目はPicoSvcでは生成しません。', formsRedirect:'通常のHTMLフォーム送信では202のJSON応答が表示されます。完了ページへ移動したい場合はフォームの設定APIでsuccessRedirectを設定してください。ファイル添付（multipart）は受け付けません。', mailNote:'Mailはあなたがメール用DNSを設定するサービスではありません。PicoSvcが発行する受信アドレスにメールを送ります。ただし運営者による受信設定と実際の送受信確認が終わるまでは本番で使えるとみなさないでください。', mockTitle:'ダッシュボードと操作画面の使い分け', mockBody:'説明ページはログイン不要。操作ページは作成・編集・履歴確認。全体ダッシュボードは16サービスの利用量とリンクをまとめます。' },
  en: { index:'Customer documentation', intro:'Practical instructions for all 16 services: what to prepare, what to enter, and what you receive. Provider setup is never a customer prerequisite.', home:'All services', dashboard:'All-service dashboard', explain:'Product overview', open:'Workspace', steps:'Steps in the workspace', before:'What you prepare', sample:'Example request / integration', api:'Management API entry point', after:'Before relying on it', note:'Examples use placeholders: replace $BASE_URL, $SESSION_TOKEN and issued URLs with real values. Never publish session tokens or API keys in a webpage or repository.', limitations:'What it does not do', compare:'Feature comparison and sources', back:'All documentation', formsTitle:'Forms gives you a submission endpoint, not a visual form builder', formsDetail:'Create a Form in PicoSvc and copy the returned endpoint. Put the HTML below on your own site and replace the action URL with that endpoint. Submissions are stored in the workspace. PicoSvc does not create the form UI or CSS.', formsRedirect:'A plain HTML form normally displays the JSON 202 response. To send visitors to a thank-you page, configure successRedirect using the form configuration API. Multipart file uploads are unsupported.', mailNote:'Mail does not require you to configure email DNS. Send mail to the address issued by PicoSvc. Do not consider mail receiving production-ready until the operator has configured incoming mail and verified end-to-end delivery.', mockTitle:'Overview, workspace, and dashboard', mockBody:'The product overview is public. The workspace handles creation, editing and history. The all-service dashboard shows usage and links for all 16 tools.' },
  'zh-CN': { index:'客户使用文档', intro:'逐项说明 16 项服务需要准备什么、输入什么、会得到什么；不把平台部署工作转嫁给用户。', home:'全部服务', dashboard:'全部服务总览', explain:'产品介绍', open:'工作台', steps:'工作台操作步骤', before:'用户需要准备', sample:'调用与集成示例', api:'管理 API 入口', after:'正式使用前', note:'示例包含占位值；请替换 $BASE_URL、$SESSION_TOKEN 和生成的 URL。不要将令牌或 API 密钥发布到网站或仓库。', limitations:'不支持的功能', compare:'功能比较与资料来源', back:'全部文档', formsTitle:'Forms 提供提交接口，而不是可视化表单设计器', formsDetail:'在 PicoSvc 创建表单并复制返回的 endpoint，将下面的 HTML 放到自己的网站，把 action 替换成生成地址。提交内容保存在工作台。PicoSvc 不自动生成表单外观或 CSS。', formsRedirect:'普通 HTML 表单提交后通常会显示 202 JSON。如需跳转感谢页面，请通过表单配置 API 设置 successRedirect。不支持 multipart 文件上传。', mailNote:'Mail 不要求用户配置邮件 DNS。向 PicoSvc 生成的地址发邮件即可；运营方尚未完成入站配置及端到端测试前，请勿视为可投入生产。', mockTitle:'介绍、工作台和总览', mockBody:'产品介绍无需登录，工作台用于创建、编辑及查看历史，总览显示全部 16 项服务的用量和链接。' },
} as const;

const SAMPLES: Record<ProductSlug, string> = {
  mcp: `# Workspace: enter a GitHub repository URL, branch, and access mode.\n# When the deployment finishes, copy the actual connection URL.\n# Client settings vary: paste that URL in your MCP client's remote-server configuration.`,
  mock: `# After creating a GET /products mock, copy the issued endpoint URL.\ncurl -i "$MOCK_ENDPOINT"\n# Change status to 500 in the workspace to test an error state.`,
  hooks: `# After creating an inbox, copy its receiving URL.\ncurl -i -X POST "$INBOX_URL" \\\n  -H 'Content-Type: application/json' \\\n  --data '{"event":"payment.test","orderId":"sample-123"}'\n# Return to the workspace and open Received events.`,
  rss: `# Create a feed from a public page in the workspace.\n# Copy the feedUrl from the creation result.\ncurl -i "$FEED_URL"\n# Paste the same URL into your RSS reader.`,
  mail: `# 1. Create a Hooks inbox and copy its receiving URL.\n# 2. Create a Mail route, using the Hooks URL as webhookUrl.\n# 3. Copy the issued address: RANDOM_ID@picosvc.com\n# 4. Send a test email from your mail client.\n# 5. Check Mail delivery history AND the Hooks event body.`,
  shot: `# Run only from a trusted terminal or backend.\ncurl --fail-with-body -X POST "$BASE_URL/api/picosvc/shot" \\\n  -H "Authorization: Bearer $SESSION_TOKEN" \\\n  -H 'Content-Type: application/json' \\\n  --data '{"url":"https://example.com/","format":"png","width":1280,"height":720}' \\\n  --output capture.png`,
  fetch: `curl --fail-with-body -X POST "$BASE_URL/api/picosvc/fetch" \\\n  -H "Authorization: Bearer $SESSION_TOKEN" \\\n  -H 'Content-Type: application/json' \\\n  --data '{"url":"https://example.com/","format":"metadata"}'\n# Response is JSON, not raw Markdown.`,
  qr: `# Create a QR redirect in the workspace, then copy its svgPath URL.\ncurl --fail-with-body "$QR_SVG_URL" --output event.svg\n# Keep the QR image: edit targetUrl later to change its destination.`,
  cron: `# Example: every day at midnight UTC\n# Enter this five-field cron expression in the workspace:\n0 0 * * *\n# Method: POST; Target: your own HTTPS URL.\n# Open the job's run history to inspect failures.`,
  functions: `// Example source for the workspace editor:\nexport default {\n  async fetch(request) {\n    const name = new URL(request.url).searchParams.get('name') || 'world';\n    return Response.json({ hello: name });\n  }\n};\n// After creation, call the actual runtime URL from the result.`,
  json: `# Copy the endpoint and one-time bearerToken when creating a store.\ncurl -X PUT "$STORE_URL/preferences" \\\n  -H "Authorization: Bearer $STORE_TOKEN" \\\n  -H 'Content-Type: application/json' \\\n  --data '{"theme":"dark"}'\ncurl -H "Authorization: Bearer $STORE_TOKEN" "$STORE_URL/preferences"`,
  files: `# Create a space in the workspace; copy its real SPACE_ID.\ncurl --fail-with-body -X PUT \\\n  "$BASE_URL/api/picosvc/files/spaces/$SPACE_ID/object?path=logo.png" \\\n  -H "Authorization: Bearer $SESSION_TOKEN" \\\n  -H 'Content-Type: image/png' --data-binary @logo.png\n# The JSON response contains publicUrl. Do not upload secrets.`,
  license: `# Create a project, then issue a key in the workspace.\ncurl -X POST "$VALIDATION_URL" \\\n  -H 'Content-Type: application/json' \\\n  --data '{"key":"PASTE_ISSUED_LICENSE_KEY"}'\n# Inspect valid: true/false, reason, and expiration.`,
  flags: `# Create a project; set maintenance to true in its workspace.\ncurl --fail-with-body "$FLAGS_URL"\n# Example response: {"project":"My app","flags":{"maintenance":true}}\n# Do not put passwords in published flag values.`,
  monitor: `# Enter a public URL and a 60-minute interval on Free.\n# Optional: add a webhook endpoint for notifications.\n# Use the Monitor workspace to preview content and review change/error history.`,
  forms: `<form action="https://YOUR_ISSUED_ENDPOINT/forms/PUBLIC_ID" method="POST">\n  <label>Name <input name="name" required></label>\n  <label>Email <input name="email" type="email" required></label>\n  <label>Message <textarea name="message" required></textarea></label>\n  <button type="submit">Send</button>\n</form>\n<!-- Replace action with the exact endpoint returned by PicoSvc. -->`,
};

export default function CustomerDocsIndex({ locale }: { locale: Locale }) {
  const lang = locale === 'zh-CN' ? 'zh-cn' : locale;
  const c = LABELS[locale];
  return <main className="customerDocs"><nav className="customerNav shell"><a className="customerBrand" href={`/${lang}/`}><img src="/icons/picosvc.svg" width="34" height="34" alt=""/>PicoSvc</a><div className="customerNavLinks"><a href={`/${lang}/`}>{c.home}</a><a href={`/${lang}/dashboard/`}>{c.dashboard}</a></div></nav><div className="shell customerBody"><h1>{c.index}</h1><p>{c.intro}</p><div className="customerDocsGrid">{CUSTOMER_SLUGS.map(service => <article key={service}><img src={`/icons/${service}.svg`} width="46" height="46" alt=""/><h2><a href={`/${lang}/docs/${service}/`}>{SERVICE_INFO[service].name} →</a></h2><p>{CUSTOMER_GUIDES[service].summary[locale]}</p><a href={`/${lang}/${service}/app/`}>{c.open} ↗</a></article>)}</div></div></main>;
}

export function CustomerServiceDocs({ service, locale }: { service: ProductSlug; locale: Locale }) {
  const lang = locale === 'zh-CN' ? 'zh-cn' : locale;
  const c = LABELS[locale];
  const guide = CUSTOMER_GUIDES[service];
  return <main className="customerDocs"><nav className="customerNav shell"><a className="customerBrand" href={`/${lang}/docs/`}><img src="/icons/picosvc.svg" width="34" height="34" alt=""/>PicoSvc · {c.index}</a><div className="customerNavLinks"><a href={`/${lang}/${service}/`}>{c.explain}</a><a href={`/${lang}/${service}/app/`}>{c.open}</a><a href={`/${lang}/dashboard/`}>{c.dashboard}</a></div></nav><div className="shell customerBody"><p><a className="customerInline" href={`/${lang}/docs/`}>← {c.back}</a></p><h1>{SERVICE_INFO[service].name} · {c.index}</h1><p>{guide.summary[locale]}</p>
    {service === 'forms' && <aside className="customerDocNotice"><strong>{c.formsTitle}</strong><p>{c.formsDetail}</p></aside>}
    <section className="customerSection"><h2>{c.before}</h2><p>{guide.prerequisite[locale]}</p><h2 className="customerStepsTitle">{c.steps}</h2><ol className="customerSteps">{guide.steps.map((step, i) => <li key={i}><span>{String(i + 1).padStart(2,'0')}</span>{step[locale]}</li>)}</ol></section>
    <section className="customerSection"><h2>{c.sample}</h2><p>{guide.example[locale]}</p><pre className="customerCode"><code>{SAMPLES[service]}</code></pre><p className="customerFine">{c.note}</p>{service === 'forms' && <p className="customerDocNotice">{c.formsRedirect}</p>}{service === 'mail' && <p className="customerDocNotice">{c.mailNote}</p>}</section>
    <section className="customerSection"><h2>{c.api}</h2><pre className="customerCode"><code>{guide.api}</code></pre><p>{guide.input[locale]}</p><p>{guide.output[locale]}</p></section>
    <section className="customerSection"><h2>{c.limitations}</h2><p>{guide.limitation[locale]}</p><h2>{c.compare}</h2><p><strong>{guide.competitor.axis[locale]}：</strong>{guide.competitor.pico[locale]}</p><p>{guide.competitor.name}：{guide.competitor.other[locale]}</p><a className="customerInline" href={guide.competitor.url} target="_blank" rel="noopener noreferrer">{c.compare} · {guide.competitor.name} ↗</a></section>
    <section className="customerSection customerDocNotice"><strong>{c.mockTitle}</strong><p>{c.mockBody}</p><div className="customerBottom"><a className="customerPrimary" href={`/${lang}/${service}/app/`}>{c.open} →</a><a href={`/${lang}/${service}/`}>{c.explain} →</a><a href={`/${lang}/dashboard/`}>{c.dashboard} →</a></div></section>
  </div></main>;
}
