export type LegalLocale = 'en' | 'ja' | 'zh-CN';
export type LegalSection = { title: string; paragraphs: string[]; subheadings?: { title: string; paragraphs: string[] }[] };
export type LegalDocument = { title: string; badge: string; effective?: string; intro?: string; note?: string; sections: LegalSection[] };

const termsEn: LegalDocument = {
  title: 'Terms of Service', badge: 'Legal', effective: 'Effective September 16, 2026',
  intro: 'These Terms of Service (the “Terms”) govern access to and use of PicoSvc websites, APIs, dashboards, runtime endpoints, developer tools, and related services (collectively, the “Service”). By creating an account, purchasing a plan, or using the Service, you agree to these Terms.',
  sections: [
    { title: '1. Accounts and eligibility', paragraphs: ['You must be legally able to enter into these Terms. If you use the Service for an organization, you represent that you are authorized to act for that organization. You are responsible for your account, API tokens, deployment credentials, connected repositories, and all activity performed through them. Keep credentials secure and promptly rotate credentials you believe may have been exposed.'] },
    { title: '2. PicoSvc products, separate plans, and bundles', paragraphs: ['PicoSvc consists of multiple developer services. Unless a checkout page expressly says otherwise, each product is sold and metered separately. Purchasing a plan for one product does not automatically upgrade or unlock another product.', 'PicoSvc may also offer bundles that include specified plans or quotas for multiple products at a combined price. A bundle grants only the products and limits shown at purchase. If a standalone product plan and a bundle overlap, the Service may apply the higher applicable entitlement for that product, subject to the checkout terms for that offer.', 'Product features, quotas, prices, taxes, billing intervals, and included usage are the values shown on the applicable pricing or checkout page at the time of purchase. Free plans and trial features may have lower limits or additional restrictions.'] },
    { title: '3. Billing, renewal, cancellation, and refunds', paragraphs: ['Paid subscriptions renew automatically for the billing period shown at checkout until cancelled. You authorize PicoSvc and its payment processor to charge applicable fees and taxes using your selected payment method. You may cancel a subscription through the available billing controls; cancellation normally takes effect at the end of the paid billing period unless the checkout flow states otherwise.', 'Fees are non-refundable except where required by law or where PicoSvc expressly states otherwise. We may change future pricing or plan contents. Material changes to a recurring paid plan will be communicated through the Service or another reasonable channel before they take effect for a future renewal.'] },
    { title: '4. Usage limits and service protection', paragraphs: ['Plans may include limits on requests, endpoints, deployments, builds, storage, execution time, bandwidth, events, or other resources. We may rate-limit, delay, reject, pause, or suspend usage that exceeds the purchased limits or threatens the reliability or security of the Service. We may impose reasonable technical limits to prevent abuse even where a plan does not display a specific limit.'] },
    { title: '5. Acceptable use', paragraphs: ['You may not use the Service to violate law, infringe intellectual property or privacy rights, distribute malware, steal credentials, conduct unauthorized security testing, send unlawful or abusive spam, evade platform restrictions, operate deceptive or fraudulent systems, interfere with other users, attack third-party systems, or consume resources in a manner intended to degrade or circumvent the Service. You may not use PicoSvc to access or process third-party systems or data unless you have permission to do so.', 'Some products can execute user-supplied code or forward user-supplied traffic. You are responsible for the code, endpoints, payloads, recipients, data sources, and third-party terms associated with your use.'] },
    { title: '6. Your content and code', paragraphs: ['You retain ownership of repositories, code, files, payloads, mock responses, configuration, and other content you submit to the Service (“User Content”). You grant PicoSvc a limited, non-exclusive license to host, copy, transmit, cache, transform, execute, and otherwise process User Content only as reasonably necessary to provide, secure, troubleshoot, and improve the Service.', 'You represent that you have the rights needed to submit and process User Content through PicoSvc. You are responsible for backups of important data and for removing secrets or personal data that are not needed for the Service.'] },
    { title: '7. Third-party services', paragraphs: ['PicoSvc may integrate with third parties such as identity providers, cloud infrastructure providers, source-code hosts, payment processors, or external APIs. Your use of those third-party services may also be governed by their terms. PicoSvc is not responsible for outages, policy changes, account restrictions, or other acts of third-party providers outside PicoSvc’s reasonable control.'] },
    { title: '8. Security and beta functionality', paragraphs: ['We use reasonable technical and organizational measures designed to protect the Service, but no online service can guarantee absolute security or uninterrupted operation. Some PicoSvc products or features may be labeled beta, preview, experimental, or early access. Such features may change, fail, or be discontinued without the same notice or support expectations as generally available features.'] },
    { title: '9. Suspension and termination', paragraphs: ['You may stop using the Service at any time. We may suspend or terminate access where reasonably necessary to address non-payment, security risk, abusive behavior, legal obligations, material breach of these Terms, or danger to other users or systems. Where practical, we will provide notice and an opportunity to resolve the issue.'] },
    { title: '10. Changes to the Service', paragraphs: ['We may add, remove, or modify features, plans, quotas, integrations, domains, or runtime behavior. We will use reasonable efforts to avoid materially disrupting paid functionality without notice, but we do not promise that every feature will remain available permanently.'] },
    { title: '11. Disclaimers', paragraphs: ['To the maximum extent permitted by law, the Service is provided on an “as is” and “as available” basis. PicoSvc disclaims implied warranties of merchantability, fitness for a particular purpose, non-infringement, and uninterrupted or error-free operation. PicoSvc does not guarantee that generated outputs, remote conversions, screenshots, fetched content, scheduled jobs, webhooks, or third-party integrations will always be complete, accurate, timely, or available.'] },
    { title: '12. Limitation of liability', paragraphs: ['To the maximum extent permitted by law, PicoSvc will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, revenue, data, goodwill, or business opportunities. PicoSvc’s aggregate liability arising from the Service will not exceed the greater of the amount you paid to PicoSvc for the affected Service during the 12 months before the event giving rise to the claim or USD 100. This section does not limit liability that cannot legally be limited.'] },
    { title: '13. Indemnity', paragraphs: ['To the extent permitted by law, you agree to be responsible for claims, losses, or costs arising from your unlawful use of the Service, your User Content, or your violation of third-party rights or these Terms.'] },
    { title: '14. Governing law and disputes', paragraphs: ['These Terms are governed by the laws of Japan, without regard to conflict-of-law rules. Unless mandatory law requires otherwise, the Tokyo District Court will have exclusive jurisdiction over disputes arising from these Terms or the Service.'] },
    { title: '15. Changes to these Terms', paragraphs: ['We may update these Terms as the Service evolves. The effective date above will be updated when changes are posted. If a change materially affects your rights under a paid subscription, we will provide reasonable notice through the Service or another appropriate channel.'] },
    { title: '16. Contact', paragraphs: ['For legal or support questions, use the contact or support channel displayed on the PicoSvc website or account dashboard. Do not include passwords, private keys, API secrets, or other sensitive credentials in support messages.'] },
  ]
};

const termsJa: LegalDocument = {
  title: '利用規約', badge: '法務', effective: '施行日：2026年9月16日',
  intro: '本利用規約（以下「本規約」）は、PicoSvcのウェブサイト、API、ダッシュボード、ランタイムエンドポイント、開発者向けツールおよび関連サービス（以下総称して「本サービス」）の利用条件を定めるものです。アカウントの作成、有料プランの購入、または本サービスの利用により、本規約に同意したものとみなされます。',
  sections: [
    { title: '1. アカウントおよび利用資格', paragraphs: ['利用者は本規約を有効に締結できる法的能力を有している必要があります。組織のために利用する場合、当該組織を代表する権限を有することを表明するものとします。アカウント、APIトークン、デプロイ資格情報、接続済みリポジトリ、およびそれらを通じた活動の管理責任は利用者にあります。認証情報は安全に管理し、漏えいの可能性がある場合は速やかにローテーションしてください。'] },
    { title: '2. PicoSvc製品、個別プランおよびBundle', paragraphs: ['PicoSvcは複数の開発者向けサービスで構成されています。購入画面に別段の明示がない限り、各製品は個別に販売・計測され、ある製品のプランを購入しても別製品が自動的にアップグレードまたは解放されることはありません。', '複数製品の指定プランまたは利用枠をまとめたBundleを提供する場合があります。Bundleで付与されるのは購入時に明示された製品と上限のみです。単品プランとBundleが重複する場合、購入条件に従い、その製品についてより高い権限を適用することがあります。', '機能、利用上限、価格、税、請求周期および含まれる利用量は、購入時の料金ページまたは最終確認画面に表示される内容によります。無料プランや試用機能には低い上限や追加制限が設定される場合があります。'] },
    { title: '3. 料金、更新、解約および返金', paragraphs: ['有料サブスクリプションは、解約されるまで購入画面に表示された請求期間ごとに自動更新されます。利用者は選択した支払方法により、PicoSvcおよび決済事業者が料金・税を請求することを承認します。解約は提供される請求管理機能から行うことができ、別段の表示がない限り支払済み期間の終了時に効力を生じます。', '法令上必要な場合またはPicoSvcが明示した場合を除き、料金は返金されません。将来の料金またはプラン内容を変更する場合があります。継続課金プランの重要な変更は、将来の更新に適用される前に本サービスその他合理的な方法で通知します。'] },
    { title: '4. 利用上限およびサービス保護', paragraphs: ['プランにはリクエスト数、エンドポイント数、デプロイ数、ビルド数、ストレージ、実行時間、帯域、イベント数その他のリソース上限が設定される場合があります。購入した上限を超える利用、または本サービスの信頼性・安全性を脅かす利用について、レート制限、遅延、拒否、一時停止または停止を行うことがあります。表示上の上限がない場合でも、濫用防止のため合理的な技術制限を設けることがあります。'] },
    { title: '5. 禁止事項・適正利用', paragraphs: ['法令違反、知的財産権・プライバシー権の侵害、マルウェア配布、認証情報の窃取、無許可のセキュリティテスト、違法または濫用的なスパム、プラットフォーム制限の回避、詐欺的行為、他利用者への妨害、第三者システムへの攻撃、本サービスの劣化または制限回避を目的とした過度な資源消費に本サービスを利用してはなりません。許可なく第三者のシステムやデータへアクセス・処理することも禁止します。', '一部製品は利用者提供コードの実行やトラフィック転送を行います。コード、エンドポイント、ペイロード、送信先、データソースおよび第三者サービスの利用条件については利用者が責任を負います。'] },
    { title: '6. 利用者コンテンツおよびコード', paragraphs: ['利用者が提出するリポジトリ、コード、ファイル、ペイロード、Mockレスポンス、設定その他のコンテンツ（以下「利用者コンテンツ」）の権利は利用者に帰属します。利用者は、本サービスの提供、保護、障害対応および改善に合理的に必要な範囲で、利用者コンテンツをホスト、複製、送信、キャッシュ、変換、実行その他処理する非独占的かつ限定的な権利をPicoSvcに許諾します。', '利用者は利用者コンテンツを提出・処理するために必要な権利を有していることを表明します。重要データのバックアップ、および不要な秘密情報・個人情報の削除は利用者の責任です。'] },
    { title: '7. 第三者サービス', paragraphs: ['PicoSvcは認証事業者、クラウド事業者、ソースコードホスト、決済事業者、外部API等と連携する場合があります。これら第三者サービスには各事業者の規約が適用されることがあります。PicoSvcの合理的支配を超える第三者の障害、ポリシー変更、アカウント制限その他の行為について、PicoSvcは責任を負いません。'] },
    { title: '8. セキュリティおよびベータ機能', paragraphs: ['本サービスを保護するため合理的な技術的・組織的措置を講じますが、完全な安全性または無停止運用を保証するものではありません。beta、preview、experimental、early access等と表示される機能は、一般提供機能と同等の予告・サポートなく変更、障害または終了する場合があります。'] },
    { title: '9. 利用停止および終了', paragraphs: ['利用者はいつでも利用を終了できます。未払い、セキュリティリスク、濫用、法的義務、本規約の重大な違反、他利用者またはシステムへの危険に対応するため合理的に必要な場合、アクセスを停止または終了することがあります。可能な場合は通知および是正の機会を提供します。'] },
    { title: '10. サービス変更', paragraphs: ['機能、プラン、上限、連携、ドメイン、ランタイム挙動を追加・削除・変更する場合があります。有料機能への重大な影響を予告なく生じさせないよう合理的に努めますが、すべての機能が恒久的に提供されることは保証しません。'] },
    { title: '11. 免責', paragraphs: ['法令で許される最大限の範囲で、本サービスは「現状有姿」かつ「提供可能な範囲」で提供されます。商品性、特定目的適合性、非侵害性、無停止・無エラー運用に関する黙示保証を否認します。生成結果、Remote変換、スクリーンショット、取得コンテンツ、定期ジョブ、Webhook、第三者連携が常に完全・正確・適時・利用可能であることを保証しません。'] },
    { title: '12. 責任制限', paragraphs: ['法令で許される最大限の範囲で、間接損害、偶発損害、特別損害、結果損害、懲罰的損害、逸失利益、売上、データ、信用または事業機会の喪失について責任を負いません。本サービスに起因するPicoSvcの総責任額は、原因事象発生前12か月に対象サービスについて利用者が支払った金額または100米ドルのいずれか高い方を上限とします。法令上制限できない責任には本項を適用しません。'] },
    { title: '13. 補償', paragraphs: ['法令で許される範囲で、利用者の違法な利用、利用者コンテンツ、第三者権利の侵害または本規約違反に起因する請求、損失または費用について利用者が責任を負うものとします。'] },
    { title: '14. 準拠法および紛争', paragraphs: ['本規約は抵触法の原則を除き日本法に準拠します。強行法規に別段の定めがある場合を除き、本規約または本サービスに関する紛争について東京地方裁判所を第一審の専属的合意管轄裁判所とします。'] },
    { title: '15. 本規約の変更', paragraphs: ['サービスの発展に応じて本規約を更新する場合があります。変更時は上記施行日を更新します。有料サブスクリプションに関する権利へ重大な影響を与える変更については、本サービスその他適切な方法で合理的な事前通知を行います。'] },
    { title: '16. お問い合わせ', paragraphs: ['法務またはサポートに関する問い合わせは、PicoSvcサイトまたはアカウントダッシュボードに表示される窓口をご利用ください。パスワード、秘密鍵、APIシークレット等の機密情報をサポートメッセージに含めないでください。'] },
  ]
};

const termsZh: LegalDocument = {
  title: '服务条款', badge: '法律', effective: '生效日期：2026年9月16日',
  intro: '本服务条款（“条款”）适用于访问和使用 PicoSvc 网站、API、控制台、运行时端点、开发者工具及相关服务（统称“服务”）。创建账号、购买套餐或使用服务即表示你同意本条款。',
  sections: [
    { title: '1. 账号与资格', paragraphs: ['你必须具备依法订立本条款的能力。代表组织使用服务时，你声明已获得代表该组织行事的授权。你负责账号、API token、部署凭据、已连接仓库以及通过这些凭据进行的全部活动。请妥善保护凭据，并在怀疑泄露时及时轮换。'] },
    { title: '2. PicoSvc 产品、独立套餐与 Bundle', paragraphs: ['PicoSvc 由多个开发者服务组成。除结账页面明确说明外，各产品单独销售和计量。购买某一产品的套餐不会自动升级或解锁其他产品。', 'PicoSvc 也可能提供 Bundle，以组合价格包含多个产品的指定套餐或配额。Bundle 只授予购买时明确列出的产品和限制。单品套餐与 Bundle 重叠时，服务可根据该优惠的结账条款，对相关产品采用更高的有效权益。', '产品功能、配额、价格、税费、计费周期和包含用量，以购买时相应价格页或结账页显示的内容为准。免费套餐和试用功能可能具有更低限制或额外约束。'] },
    { title: '3. 计费、续费、取消与退款', paragraphs: ['付费订阅会按结账时显示的计费周期自动续订，直至取消。你授权 PicoSvc 及其支付处理方使用所选支付方式收取适用费用和税款。可通过提供的计费管理功能取消订阅；除结账流程另有说明外，取消通常在已付费周期结束时生效。', '除法律要求或 PicoSvc 明确说明外，已支付费用不予退还。我们可能调整未来价格或套餐内容。对持续付费套餐的重大变更，会在其适用于未来续费前通过服务或其他合理方式通知。'] },
    { title: '4. 使用限制与服务保护', paragraphs: ['套餐可能限制请求、端点、部署、构建、存储、执行时间、带宽、事件或其他资源。对于超过已购限制或威胁服务可靠性、安全性的使用，我们可实施限速、延迟、拒绝、暂停或停用。即使套餐未展示具体限制，也可能为防止滥用设置合理技术限制。'] },
    { title: '5. 可接受使用', paragraphs: ['不得使用服务从事违法行为、侵犯知识产权或隐私权、传播恶意软件、窃取凭据、未经授权的安全测试、违法或骚扰性垃圾信息、绕过平台限制、欺诈、干扰其他用户、攻击第三方系统，或故意消耗资源以降低或规避服务限制。未经许可，不得利用 PicoSvc 访问或处理第三方系统或数据。', '部分产品可执行用户提供的代码或转发用户流量。你需对代码、端点、payload、接收方、数据源及相关第三方条款负责。'] },
    { title: '6. 你的内容与代码', paragraphs: ['你保留对提交至服务的仓库、代码、文件、payload、Mock 响应、配置及其他内容（“用户内容”）的所有权。你授予 PicoSvc 有限、非独占的许可，仅在提供、保护、排障和改进服务所合理必要的范围内，对用户内容进行托管、复制、传输、缓存、转换、执行和其他处理。', '你声明拥有通过 PicoSvc 提交和处理用户内容所需的权利。重要数据备份以及移除服务不需要的秘密信息或个人数据由你负责。'] },
    { title: '7. 第三方服务', paragraphs: ['PicoSvc 可能集成身份提供商、云基础设施、源码托管、支付处理商或外部 API 等第三方服务。使用这些服务也可能受其自身条款约束。对于超出 PicoSvc 合理控制范围的第三方中断、政策变更、账号限制或其他行为，PicoSvc 不承担责任。'] },
    { title: '8. 安全与测试功能', paragraphs: ['我们采用合理的技术和组织措施保护服务，但任何在线服务都无法保证绝对安全或持续不中断。标记为 beta、preview、experimental 或 early access 的产品或功能，可能在没有与正式功能同等通知或支持的情况下变更、故障或停止。'] },
    { title: '9. 暂停与终止', paragraphs: ['你可随时停止使用服务。为处理未付款、安全风险、滥用、法律义务、重大违反本条款或对其他用户/系统的危险，我们可在合理必要时暂停或终止访问。在可行情况下，我们会提供通知和整改机会。'] },
    { title: '10. 服务变更', paragraphs: ['我们可能增加、删除或修改功能、套餐、配额、集成、域名或运行时行为。我们会合理努力避免在没有通知的情况下实质性影响付费功能，但不保证任何功能永久可用。'] },
    { title: '11. 免责声明', paragraphs: ['在法律允许的最大范围内，服务按“现状”和“可用状态”提供。PicoSvc 不承担适销性、特定用途适用性、不侵权、不中断或无错误运行等默示保证。我们不保证生成输出、Remote 转换、截图、抓取内容、定时任务、Webhook 或第三方集成始终完整、准确、及时或可用。'] },
    { title: '12. 责任限制', paragraphs: ['在法律允许的最大范围内，PicoSvc 不对间接、附带、特殊、后果性、示范性或惩罚性损害，以及利润、收入、数据、商誉或商业机会损失承担责任。因服务产生的 PicoSvc 总责任不超过导致索赔事件前12个月你为受影响服务支付的金额与100美元两者中的较高者。法律不得限制的责任不受本条限制。'] },
    { title: '13. 赔偿责任', paragraphs: ['在法律允许范围内，对于因你的违法使用、用户内容、侵犯第三方权利或违反本条款产生的索赔、损失或费用，你同意承担相应责任。'] },
    { title: '14. 适用法律与争议', paragraphs: ['本条款受日本法律管辖，不考虑法律冲突规则。除强制性法律另有要求外，因本条款或服务产生的争议由东京地方法院专属管辖。'] },
    { title: '15. 条款变更', paragraphs: ['随着服务发展，我们可能更新本条款，并相应更新生效日期。若变更对付费订阅下的权利产生重大影响，我们会通过服务或其他适当方式给予合理通知。'] },
    { title: '16. 联系方式', paragraphs: ['法律或支持问题请使用 PicoSvc 网站或账号控制台中显示的联系/支持渠道。请勿在支持消息中发送密码、私钥、API secret 或其他敏感凭据。'] },
  ]
};

const privacyEn: LegalDocument = {
  title: 'Privacy Policy', badge: 'Legal', effective: 'Effective September 16, 2026',
  intro: 'This Privacy Policy explains how PicoSvc collects, uses, stores, and shares information when you use PicoSvc websites, APIs, dashboards, runtime endpoints, developer tools, and related services (collectively, the “Service”).',
  sections: [
    { title: '1. Information we collect', paragraphs: [], subheadings: [
      { title: 'Account and identity information', paragraphs: ['When you sign in, our authentication provider may provide identifiers and account details such as your user ID, organization ID, email address, profile information, session information, and authentication events.'] },
      { title: 'Product and configuration data', paragraphs: ['We collect information needed to operate the PicoSvc products you use, including deployment metadata, repository references, branches, endpoint configuration, mock responses, webhook configuration, feed configuration, scheduled jobs, files, feature settings, and other product-specific data.'] },
      { title: 'Source code, secrets, and service content', paragraphs: ['Some products may need to access source code, deployment configuration, environment variables, payloads, files, URLs, email content, webhook bodies, or other content you provide. We process that content only as needed to provide, secure, troubleshoot, and maintain the requested service. Where PicoSvc supports stored deployment secrets, those secrets are intended to be encrypted at rest and are not returned in plaintext by management APIs.'] },
      { title: 'Usage and technical data', paragraphs: ['We may collect request counts, build counts, product usage, timestamps, IP addresses, user-agent information, error logs, security events, rate-limit data, diagnostic information, and similar technical information needed to operate and protect the Service.'] },
      { title: 'Billing information', paragraphs: ['If you purchase a paid product plan or bundle, our billing or payment provider may process payment-card details, billing address, tax information, subscription status, invoices, and transaction identifiers. PicoSvc generally receives subscription and payment status rather than full payment-card numbers.'] },
      { title: 'Connected third-party services', paragraphs: ['If you connect a service such as GitHub, we may receive repository identifiers, installation information, account identifiers, authorization metadata, and data necessary to perform the actions you request. Short-lived access credentials may be used to retrieve private repository content when required.'] },
    ] },
    { title: '2. How we use information', paragraphs: ['We use information to provide and operate PicoSvc; authenticate users; enforce product plans, bundles, quotas, and rate limits; deploy and run services; process requests; troubleshoot failures; secure accounts and infrastructure; prevent fraud and abuse; communicate service changes; process billing; comply with legal obligations; and improve reliability and product design.', 'We do not sell personal information. We do not use private service content such as repository code, secrets, webhook payloads, or files for third-party targeted advertising.'] },
    { title: '3. Product plans and bundles', paragraphs: ['PicoSvc products are normally subscribed to separately. We store product-level entitlement and usage information so that access to one product does not automatically grant access to another. If you purchase a bundle, we may store bundle identifiers and the product entitlements granted by that bundle.'] },
    { title: '4. Service providers and sharing', paragraphs: ['We may share information with vendors that help us provide the Service, such as authentication providers, cloud infrastructure providers, source-code hosts, observability providers, email providers, and payment processors. These providers may process information on our behalf under their own contractual and security obligations.', 'We may also disclose information when reasonably necessary to comply with law, respond to valid legal process, protect users or the public, investigate abuse or security incidents, enforce our Terms, or complete a merger, acquisition, financing, reorganization, or sale of assets subject to appropriate protections.'] },
    { title: '5. International processing', paragraphs: ['PicoSvc and its service providers may process information in countries other than the country where you live. Those countries may have different data-protection laws. Where required, we use reasonable mechanisms intended to support lawful cross-border processing.'] },
    { title: '6. Retention', paragraphs: ['We retain account, product, billing, security, and usage information for as long as reasonably necessary to provide the Service, maintain security, resolve disputes, meet accounting or legal obligations, and enforce agreements. Product content may be deleted when you delete the associated resource or account, subject to reasonable backup, recovery, fraud-prevention, and legal-retention periods.', 'Temporary build data, runtime files, short-lived access tokens, caches, and logs may have shorter retention periods depending on the product and infrastructure provider.'] },
    { title: '7. Security', paragraphs: ['We use technical and organizational safeguards designed to protect information, including access controls, encrypted transport, isolation of untrusted workloads where appropriate, credential hashing or encryption where supported, and rate limiting. No system is perfectly secure, and we cannot guarantee that unauthorized access, loss, or misuse will never occur.'] },
    { title: '8. Your choices and rights', paragraphs: ['Depending on where you live, you may have rights to request access to, correction of, deletion of, restriction of, or information about certain personal data. You may also be able to withdraw consent or object to certain processing where applicable. We may need to verify your identity before fulfilling a request, and some information may be retained where legally permitted or required.', 'You can remove many product resources directly through the Service. You can also disconnect third-party integrations through PicoSvc or the third party where available.'] },
    { title: '9. Cookies and similar technologies', paragraphs: ['PicoSvc and its authentication or infrastructure providers may use cookies, local storage, or similar technologies for sign-in, security, session management, preferences, abuse prevention, and core functionality. We may also use limited analytics to understand aggregate Service usage.'] },
    { title: '10. Children', paragraphs: ['The Service is intended for developers and organizations and is not directed to children who cannot lawfully consent to the processing of their personal information or enter into the applicable Terms. If you believe a child has provided personal information without appropriate authorization, contact us through the private support channel displayed in the Service.'] },
    { title: '11. Changes to this Policy', paragraphs: ['We may update this Privacy Policy as PicoSvc adds products, providers, or legal requirements. We will update the effective date above and provide additional notice when a change materially affects how we handle personal information.'] },
    { title: '12. Contact', paragraphs: ['For privacy questions or data-rights requests, use the private contact or support channel displayed on the PicoSvc website or in your account dashboard. Do not send passwords, private keys, API secrets, or other sensitive credentials in a support request.'] },
  ]
};

const privacyJa: LegalDocument = {
  title: 'プライバシーポリシー', badge: '法務', effective: '施行日：2026年9月16日', intro: '本プライバシーポリシーは、PicoSvcのウェブサイト、API、ダッシュボード、ランタイムエンドポイント、開発者向けツールおよび関連サービス（以下「本サービス」）の利用に際して、PicoSvcが情報をどのように取得、利用、保存、共有するかを説明するものです。',
  sections: [
    { title: '1. 取得する情報', paragraphs: [], subheadings: [
      { title: 'アカウント・本人識別情報', paragraphs: ['ログイン時、認証事業者からユーザーID、Organization ID、メールアドレス、プロフィール情報、セッション情報、認証イベント等の識別子・アカウント情報を受け取る場合があります。'] },
      { title: '製品・設定データ', paragraphs: ['デプロイメタデータ、リポジトリ参照、ブランチ、endpoint設定、Mockレスポンス、Webhook設定、feed設定、定期ジョブ、ファイル、機能設定その他製品固有データなど、利用中のPicoSvc製品を運用するために必要な情報を取得します。'] },
      { title: 'ソースコード、Secrets、サービスコンテンツ', paragraphs: ['一部製品では、ソースコード、デプロイ設定、環境変数、payload、ファイル、URL、メール内容、Webhook bodyその他利用者が提供するコンテンツへアクセスする必要があります。これらは要求されたサービスの提供、保護、障害対応、保守に必要な範囲で処理します。保存型deployment secretに対応する場合、原則として保存時暗号化を行い、管理APIから平文で返却しない設計とします。'] },
      { title: '利用・技術データ', paragraphs: ['request数、build数、製品利用量、時刻、IPアドレス、User-Agent、error log、security event、rate-limit情報、診断情報等、本サービスの運用・保護に必要な技術情報を取得する場合があります。'] },
      { title: '決済情報', paragraphs: ['有料製品またはBundleを購入する場合、決済事業者がカード情報、請求先住所、税情報、subscription状態、invoice、transaction identifier等を処理する場合があります。PicoSvcは通常、完全なカード番号ではなくsubscription・決済状態を受け取ります。'] },
      { title: '接続された第三者サービス', paragraphs: ['GitHub等を接続した場合、repository ID、installation情報、account identifier、authorization metadata、要求された操作に必要なデータを受け取る場合があります。必要に応じて短寿命のaccess credentialを使用してprivate repositoryを取得します。'] },
    ] },
    { title: '2. 情報の利用目的', paragraphs: ['PicoSvcの提供・運用、認証、製品プラン・Bundle・quota・rate limitの適用、デプロイ・実行、request処理、障害対応、アカウント・インフラの保護、不正・濫用防止、サービス変更の通知、決済処理、法的義務への対応、信頼性および製品設計の改善に情報を利用します。', '個人情報を販売しません。また、repository code、secret、webhook payload、file等のprivate service contentを第三者のターゲティング広告に利用しません。'] },
    { title: '3. 製品プランおよびBundle', paragraphs: ['PicoSvc製品は原則として個別契約です。ある製品へのアクセスが別製品を自動的に付与しないよう、製品単位のentitlement・利用量を保存します。Bundleを購入した場合、Bundle IDおよび当該Bundleから付与される製品権限を保存する場合があります。'] },
    { title: '4. 委託先・共有', paragraphs: ['認証、クラウド基盤、ソースコードホスティング、observability、メール、決済等、本サービス提供を支援する事業者に情報を共有する場合があります。これらの事業者は各自の契約上・セキュリティ上の義務に従い、当方のために情報を処理する場合があります。', 'また、法令遵守、有効な法的手続への対応、利用者・公衆の保護、濫用・security incident調査、規約執行、または適切な保護を伴う合併・買収・資金調達・組織再編・資産売却に合理的に必要な場合、情報を開示することがあります。'] },
    { title: '5. 国外での処理', paragraphs: ['PicoSvcおよび委託先は、利用者の居住国外で情報を処理する場合があります。当該国の個人情報保護法制が異なる場合があります。必要に応じて、適法な越境処理を支える合理的な措置を講じます。'] },
    { title: '6. 保存期間', paragraphs: ['アカウント、製品、決済、security、usage情報は、サービス提供、安全性維持、紛争解決、会計・法的義務、契約執行に合理的に必要な期間保存します。製品コンテンツは関連リソースまたはアカウント削除時に削除されることがありますが、backup、recovery、不正防止、法的保存期間のため一定期間残る場合があります。', '一時buildデータ、runtime file、短寿命access token、cache、log等は、製品・基盤事業者に応じてより短い保持期間となる場合があります。'] },
    { title: '7. セキュリティ', paragraphs: ['アクセス制御、通信暗号化、必要に応じたuntrusted workloadの隔離、credential hashing・暗号化、rate limiting等、情報保護を目的とする技術的・組織的対策を講じます。ただし、完全に安全なシステムは存在せず、不正アクセス、消失、濫用が絶対に発生しないことは保証できません。'] },
    { title: '8. 利用者の選択・権利', paragraphs: ['居住地域に応じて、一定の個人データについてアクセス、訂正、削除、利用制限、情報提供等を求める権利を有する場合があります。また、適用される場合は同意撤回または一定の処理への異議申立てが可能です。請求対応前に本人確認を行う場合があり、法令で許可・要求される情報は保存する場合があります。', '多くの製品リソースは本サービス上から直接削除できます。第三者連携もPicoSvcまたは第三者側で切断できる場合があります。'] },
    { title: '9. Cookie等', paragraphs: ['PicoSvcおよび認証・インフラ事業者は、ログイン、security、session管理、設定、濫用防止、コア機能のためCookie、localStorageその他類似技術を使用する場合があります。集計された利用状況を理解するため限定的なanalyticsを使用する場合もあります。'] },
    { title: '10. 子どもの利用', paragraphs: ['本サービスは開発者・組織向けであり、個人情報処理への同意または規約締結を法的に行えない子どもを対象としていません。適切な承認なく子どもが個人情報を提供したと思われる場合は、本サービスに表示される非公開サポート窓口へ連絡してください。'] },
    { title: '11. ポリシーの変更', paragraphs: ['製品、委託先、法的要件の追加等に応じて本ポリシーを更新する場合があります。上記施行日を更新し、個人情報の取扱いに重大な影響がある変更については追加通知を行います。'] },
    { title: '12. お問い合わせ', paragraphs: ['プライバシーまたはデータ権利に関する請求は、PicoSvcサイトまたはアカウントダッシュボードに表示される非公開連絡・サポート窓口をご利用ください。パスワード、秘密鍵、API secretその他の機密credentialを送信しないでください。'] },
  ]
};

const privacyZh: LegalDocument = {
  title: '隐私政策', badge: '法律', effective: '生效日期：2026年9月16日', intro: '本隐私政策说明当你使用 PicoSvc 网站、API、控制台、运行时端点、开发者工具及相关服务（统称“服务”）时，我们如何收集、使用、存储和共享信息。',
  sections: [
    { title: '1. 我们收集的信息', paragraphs: [], subheadings: [
      { title: '账号与身份信息', paragraphs: ['登录时，身份认证提供商可能向我们提供用户ID、Organization ID、邮箱、个人资料、session信息和认证事件等标识符及账号信息。'] },
      { title: '产品与配置数据', paragraphs: ['我们会收集运行你所使用 PicoSvc 产品所需的信息，包括部署元数据、仓库引用、分支、endpoint配置、Mock响应、Webhook配置、feed配置、定时任务、文件、功能设置及其他产品特定数据。'] },
      { title: '源代码、Secrets 与服务内容', paragraphs: ['部分产品可能需要访问源代码、部署配置、环境变量、payload、文件、URL、邮件内容、Webhook body或你提供的其他内容。我们仅在提供、保护、排障和维护所请求服务所需的范围内处理这些内容。对于 PicoSvc 支持存储的 deployment secret，设计上应在静态存储时加密，并且管理API不以明文返回。'] },
      { title: '使用与技术数据', paragraphs: ['我们可能收集request数量、build数量、产品用量、时间戳、IP地址、User-Agent、error log、security event、rate-limit信息、诊断信息及其他运行和保护服务所需的技术数据。'] },
      { title: '计费信息', paragraphs: ['购买付费产品或Bundle时，计费/支付提供商可能处理银行卡详情、账单地址、税务信息、subscription状态、invoice和交易标识。PicoSvc通常接收subscription和支付状态，而非完整卡号。'] },
      { title: '已连接的第三方服务', paragraphs: ['连接GitHub等服务时，我们可能接收repository identifier、installation信息、account identifier、authorization metadata及执行你所请求操作所需的数据。必要时会使用短期access credential读取private repository。'] },
    ] },
    { title: '2. 信息用途', paragraphs: ['我们使用信息来提供和运营PicoSvc、认证用户、执行产品套餐/Bundle/配额/rate limit、部署和运行服务、处理请求、排障、保护账号和基础设施、防止欺诈与滥用、通知服务变更、处理计费、履行法律义务并改进可靠性和产品设计。', '我们不出售个人信息，也不会将repository code、secret、webhook payload、file等private service content用于第三方定向广告。'] },
    { title: '3. 产品套餐与Bundle', paragraphs: ['PicoSvc产品通常单独订阅。我们保存产品级entitlement与用量，确保访问一个产品不会自动获得另一个产品。购买Bundle时，我们可能保存Bundle标识及其授予的产品权益。'] },
    { title: '4. 服务提供商与共享', paragraphs: ['我们可能与协助提供服务的供应商共享信息，例如认证、云基础设施、源码托管、observability、邮件和支付服务商。这些供应商可能依据自身合同与安全义务代表我们处理信息。', '为遵守法律、响应有效法律程序、保护用户或公众、调查滥用或security incident、执行条款，或在适当保护下进行合并、收购、融资、重组或资产出售时，我们也可能在合理必要范围内披露信息。'] },
    { title: '5. 跨境处理', paragraphs: ['PicoSvc及其服务商可能在你居住国以外处理信息，这些国家的数据保护法律可能不同。在需要时，我们会采用合理机制以支持合法的跨境处理。'] },
    { title: '6. 保存期限', paragraphs: ['账号、产品、计费、安全和usage信息会在提供服务、维护安全、解决争议、履行会计/法律义务和执行协议所合理必要的期间内保存。删除相关资源或账号后，产品内容可能被删除，但可能因backup、recovery、防欺诈或法律保存要求而保留一段时间。', '临时build数据、runtime file、短期access token、cache和log可根据产品和基础设施服务商采用更短保存期限。'] },
    { title: '7. 安全', paragraphs: ['我们采用访问控制、加密传输、必要时隔离untrusted workload、credential hashing/加密和rate limiting等技术与组织保障措施。任何系统都无法做到绝对安全，我们不能保证永远不会发生未经授权访问、丢失或滥用。'] },
    { title: '8. 你的选择与权利', paragraphs: ['根据你所在地区，你可能有权请求访问、更正、删除、限制处理或了解某些个人数据；适用时也可能可以撤回同意或反对某些处理。处理请求前我们可能需要验证身份，法律允许或要求保留的信息可能继续保存。', '很多产品资源可直接通过服务删除；第三方集成也可能通过PicoSvc或第三方服务断开。'] },
    { title: '9. Cookie及类似技术', paragraphs: ['PicoSvc及认证/基础设施服务商可能为登录、安全、session管理、偏好设置、防滥用和核心功能使用Cookie、localStorage或类似技术。我们也可能使用有限analytics了解服务的汇总使用情况。'] },
    { title: '10. 儿童', paragraphs: ['服务面向开发者和组织，并非面向无法依法同意个人信息处理或订立相关条款的儿童。如果你认为儿童在未获适当授权的情况下提供了个人信息，请通过服务中显示的私密支持渠道联系我们。'] },
    { title: '11. 政策变更', paragraphs: ['随着PicoSvc增加产品、服务商或法律要求，我们可能更新本隐私政策。我们会更新上方生效日期，并在变更实质影响个人信息处理方式时提供额外通知。'] },
    { title: '12. 联系我们', paragraphs: ['隐私问题或数据权利请求，请使用PicoSvc网站或账号控制台中显示的私密联系/支持渠道。请勿发送密码、私钥、API secret或其他敏感凭据。'] },
  ]
};

export const TERMS: Record<LegalLocale, LegalDocument> = { en: termsEn, ja: termsJa, 'zh-CN': termsZh };
export const PRIVACY: Record<LegalLocale, LegalDocument> = { en: privacyEn, ja: privacyJa, 'zh-CN': privacyZh };
