import type { Locale } from './i18n-data';
import { SERVICE_INFO, type GenericServiceSlug } from './service-data';
import { PICOSVC_PRICING, PICOSVC_QUOTAS } from './pricing-data';
import { PRODUCT_OVERVIEW } from './product-overview';
import './product-landing.css';

type Copy = { ja: string; en: string; 'zh-CN': string };
type Slug = GenericServiceSlug | 'mock';
const t = (ja: string, en: string, zh: string): Copy => ({ ja, en, 'zh-CN': zh });

/** Specific example applications, not promises of availability or an exhaustive API contract. */
const SCENARIOS: Record<Slug, { uses: readonly [Copy, Copy]; setup: Copy }> = {
  mcp: { uses: [t('社内のMCPツールをGitHubからデプロイし、保護された接続先を配布する。','Deploy an internal MCP tool from GitHub and distribute its protected endpoint.','从 GitHub 部署内部 MCP 工具并共享受保护的连接地址。'),t('検証用MCPを公開し、変更を加えたらビルド結果を確認する。','Publish a development MCP and check the build after updating its source.','发布开发用 MCP，更新代码后检查构建结果。')],setup:t('GitHubリポジトリと起動方法を準備。プライベートrepoはGitHub Appの接続も必要です。','Prepare your GitHub repository and start command. Private repos also need GitHub App access.','准备 GitHub 仓库及启动命令；私有仓库还需连接 GitHub App。') },
  mock: { uses:[t('フロントエンドの開発中に、固定JSONを返す仮のAPIを用意する。','Provide a fixed-JSON API while building a frontend.','在开发前端时提供返回固定 JSON 的模拟 API。'),t('障害系の表示を確かめるため、任意のHTTPステータスを返す。','Return a chosen HTTP status to check error-state UI.','返回指定 HTTP 状态码以测试错误界面。')],setup:t('返したいHTTPメソッド、パス、ステータス、レスポンス本文を決めます。','Decide the HTTP method, path, status, and response body.','确定 HTTP 方法、路径、状态码及响应内容。') },
  hooks: { uses:[t('決済サービスから届くWebhookのヘッダーと本文を確認する。','Inspect the headers and body of a payment-provider webhook.','检查支付服务发来的 Webhook 请求头和内容。'),t('開発環境の受信処理を直してから、保存したイベントを再送する。','Replay a captured event after fixing your development handler.','修复开发环境的接收程序后重放已捕获的事件。')],setup:t('送信元サービスに設定できるWebhook URLと、必要なら再送先を準備します。','Have a sender that accepts a webhook URL and, optionally, a replay destination.','准备可设置 Webhook URL 的发送服务，以及可选的重放目标。') },
  rss: { uses:[t('RSSがないブログ更新一覧をフィードとして購読する。','Subscribe to updates from a blog without its own RSS feed.','订阅没有 RSS 的博客更新。'),t('記事一覧のHTML構造に合わせてCSSセレクターを調整する。','Tune CSS selectors for an article listing page.','根据文章列表的 HTML 结构调整 CSS 选择器。')],setup:t('外部からアクセスでき、記事へのリンクが掲載された一覧ページを選びます。','Choose a publicly reachable listing page with links to its articles.','选择可公开访问且包含文章链接的列表页面。') },
  mail: { uses:[t('問い合わせメールを自作アプリのWebhookへ転送する。','Relay contact emails to your application webhook.','将联系邮件转发给应用 Webhook。'),t('受信したメールをイベントとして後続処理に渡す。','Pass incoming messages to a downstream event handler.','将收到的邮件作为事件传给后续处理程序。')],setup:t('HTTPSの受信先を用意し、Cloudflare側で対象ドメインのメールルーティングを設定します。','Prepare an HTTPS handler and configure email routing for the domain in Cloudflare.','准备 HTTPS 接收端，并在 Cloudflare 配置域名邮件路由。') },
  shot: { uses:[t('公開サイトの表示をPNGで撮影し、CIの成果物に保存する。','Capture a public page as PNG and save it in CI artifacts.','将公开网页截图为 PNG 并保存到 CI 构件。'),t('指定URLをPDFにして、レビュー用の資料に添付する。','Turn a public URL into PDF for a review document.','将公开 URL 转为 PDF，用于审核材料。')],setup:t('公開URLを選び、JS描画が遅いページでは待機条件を設定します。','Choose a public URL and set a wait condition for slowly rendered pages.','选择公开 URL；页面渲染较慢时设置等待条件。') },
  fetch: { uses:[t('記事URLからMarkdownを取得して、手元で要約・整理する。','Extract Markdown from one article for downstream summarization.','从单篇文章提取 Markdown 以便后续摘要。'),t('リンク先のタイトル・説明文を取得して一覧に表示する。','Extract a link title and description for an index.','提取链接标题和描述并显示在列表中。')],setup:t('認証を必要としない、公開された単一のWebページURLを準備します。','Prepare one publicly accessible webpage URL that does not require login.','准备无需登录即可访问的单个网页 URL。') },
  qr: { uses:[t('チラシのQRコードの印刷後に、リンク先だけ変更する。','Update a printed flyer’s QR destination without reprinting it.','在传单印好后只修改二维码跳转地址。'),t('イベント案内のQRを作り、終了後にアーカイブへ転送する。','Create an event QR and redirect it to an archive afterward.','创建活动二维码，活动结束后重定向到存档。')],setup:t('転送先として使う公開HTTP(S) URLを用意します。','Prepare a public HTTP(S) destination URL.','准备公开的 HTTP(S) 跳转地址。') },
  cron: { uses:[t('指定した時間に自分のHTTPSエンドポイントへPOSTする。','POST to your HTTPS endpoint on a schedule.','按计划向自己的 HTTPS 地址发送 POST。'),t('定期的なヘルスチェックを実行し、履歴で失敗を確認する。','Run a periodic health check and inspect failures in run history.','定期运行健康检查，并在执行记录中查看失败。')],setup:t('公開先URLとUTCの5フィールドCron式を決めます。','Prepare a public target URL and a five-field UTC cron expression.','准备公开目标 URL 和五字段 UTC Cron 表达式。') },
  functions: { uses:[t('小さなJSONを返すJavaScriptのHTTP関数を公開する。','Publish a small JavaScript HTTP function returning JSON.','发布返回 JSON 的轻量 JavaScript HTTP 函数。'),t('外部アプリから使う簡単な変換処理をエッジに置く。','Run a simple transformation endpoint at the edge.','在边缘运行简单的数据转换接口。')],setup:t('fetch(request)がResponseを返すJavaScriptコードを準備します。','Prepare JavaScript with a fetch(request) handler that returns a Response.','准备包含返回 Response 的 fetch(request) 处理函数的 JavaScript。') },
  json: { uses:[t('小さなアプリの設定値をキーごとのJSONとして保存する。','Store small app settings as JSON values by key.','按键保存小型应用的 JSON 设置。'),t('サーバー処理からBearerトークン付きでドキュメントを読み書きする。','Read and write documents from a server with a bearer token.','在服务器上使用 Bearer 令牌读写文档。')],setup:t('ストアを作成したときに一度だけ表示されるBearerトークンを安全に保存します。','Safely save the bearer token shown only when the store is created.','安全保存创建存储时仅显示一次的 Bearer 令牌。') },
  files: { uses:[t('Webアプリの小さな画像や静的ファイルを保管する。','Store small images or static files for a web app.','存储 Web 应用的小型图片或静态文件。'),t('アクセス設定を確認してから、公開用のアセットを配信する。','Deliver public assets after checking access settings.','检查访问设置后分发公开资源。')],setup:t('配信するファイルと公開・非公開の扱いを決め、R2設定を確認します。','Decide which files may be public and verify the R2 configuration.','确定文件公开范围并检查 R2 配置。') },
  license: { uses:[t('デスクトップアプリ向けにライセンスキーを発行する。','Issue license keys for a desktop application.','为桌面应用发放许可证密钥。'),t('利用停止したキーを無効化し、検証結果を確認する。','Revoke a key and verify that validation reflects the change.','撤销密钥并验证状态变化。')],setup:t('キーを発行する製品・プロジェクトを決めます。','Identify the product or project that will issue keys.','确定需要发放密钥的产品或项目。') },
  flags: { uses:[t('リリース済みアプリで表示する機能を設定値で切り替える。','Toggle a feature in a released app via a configuration value.','通过配置值切换已发布应用中的功能。'),t('開発環境と本番環境で別々の設定プロジェクトを作る。','Separate development and production configuration projects.','为开发和生产环境建立独立配置项目。')],setup:t('プロジェクトとアプリが読む公開設定値を決めます。機密情報は公開フラグに入れません。','Choose the project and public values your app will read. Do not put secrets in public flags.','确定项目和应用读取的公开配置值，不要放入机密。') },
  monitor: { uses:[t('募集ページのテキストが更新されたらWebhook通知を受ける。','Get a webhook notification when a listing page’s text changes.','当公告页面文字变化时接收 Webhook 通知。'),t('更新が止まったのか取得に失敗したのかを履歴で区別する。','Distinguish unchanged content from fetch errors in the event history.','在事件记录中区分内容未变与抓取失败。')],setup:t('公開ページのURL、監視間隔、必要なら通知先Webhookを準備します。','Prepare a public page URL, check interval, and optionally a notification webhook.','准备公开页面 URL、检查间隔及可选的通知 Webhook。') },
  forms: { uses:[t('静的サイトに問い合わせフォームの投稿先を設ける。','Add a submission endpoint to a static site’s contact form.','为静态网站的联系表单添加提交接口。'),t('アンケートの投稿データを管理画面で確認する。','Inspect survey submissions in the dashboard.','在控制台查看问卷提交数据。')],setup:t('フォームに必要な入力項目を決め、発行された投稿先を利用します。','Decide your form fields and use the generated submission endpoint.','确定表单字段并使用生成的提交地址。') },
};

const UI = {
  ja: { products:'全サービス', pricing:'料金・利用枠', guide:'サービスガイド', explore:'できること', scenarios:'活用例', compare:'比較', faq:'よくある質問', hero:'何ができるかを、登録前に確認。', tagline:'利用方法・料金枠・比較ポイントを先に確認し、必要になったらワークスペースへ。', try:'ワークスペースへ移動', viewPricing:'料金と詳細な上限を見る', overview:'このサービスでできること', examples:'こんな場面で使えます', exampleLabel:'利用シーン', setup:'始める前に準備すること', steps:'使い始めるまでの3ステップ', stepOne:'ログインして作成', stepTwo:'設定を確認・テスト', stepThree:'結果や公開URLを組み込む', compareTitle:'競合・代替サービスとの違い', pico:'PicoSvcの対象範囲', other:'公式資料で確認できる代替サービス', source:'公式資料を見る', caveat:'利用前の注意点', plans:'コード上のプランと利用枠', perService:'サービス単位の月額。決済画面の実際の価格・利用条件を確認してください。', question1:'ログインせずに何が見られますか？', answer1:'この紹介・料金枠・比較資料はログイン不要です。リソースの作成・編集・実行や利用履歴の確認はログインが必要です。', question2:'どのように使い始めますか？', question3:'本番で必ず動くことは確認されていますか？', answer3:'いいえ。ここに記載した機能はコードに基づく説明であり、外部サービスを使った本番環境の動作保証ではありません。実際の環境で疎通・出力・利用枠を確認してください。', disclaimer:'比較は機能の守備範囲についての説明で、価格・性能・稼働率の優劣を示すものではありません。競合の仕様はリンク先の公式資料で再確認してください。', documentation:'APIの使い方', workspace:'操作画面', free:'Free', picoPlan:'Pico', plus:'PicoPlus' },
  en: { products:'All products',pricing:'Pricing & quotas',guide:'Product guide',explore:'Features',scenarios:'Use cases',compare:'Comparison',faq:'FAQ',hero:'Understand the product before signing in.',tagline:'Explore workflows, quotas and alternatives first; open the workspace when you are ready.',try:'Go to workspace',viewPricing:'Explore full pricing and quotas',overview:'What this service does',examples:'Example use cases',exampleLabel:'Use case',setup:'What to prepare',steps:'Get started in three steps',stepOne:'Sign in and create',stepTwo:'Configure and test',stepThree:'Integrate the result or public URL',compareTitle:'Compared with alternatives',pico:'What PicoSvc focuses on',other:'What the alternative documents',source:'Read the official documentation',caveat:'Limits to consider',plans:'Code-configured plans and quotas',perService:'Monthly pricing per service. Check actual checkout prices and terms before purchasing.',question1:'What can I see without signing in?',answer1:'This guide, published quotas and comparison links are public. Sign-in is needed to create, edit or run resources and view your usage.',question2:'How do I get started?',question3:'Is production availability guaranteed?',answer3:'No. The described capabilities reflect repository code, not verified external-provider production operation. Verify connectivity, output and quotas in your environment.',disclaimer:'This compares product scope, not overall quality, live pricing, performance or uptime. Recheck the linked official documentation for changes.',documentation:'API guide',workspace:'Workspace',free:'Free',picoPlan:'Pico',plus:'PicoPlus' },
  'zh-CN': { products:'所有服务',pricing:'价格与配额',guide:'服务指南',explore:'功能',scenarios:'使用场景',compare:'对比',faq:'常见问题',hero:'登录前先了解产品。',tagline:'先了解功能、配额与同类服务；准备好后再进入工作台。',try:'进入工作台',viewPricing:'查看完整价格与配额',overview:'这个服务能做什么',examples:'典型使用场景',exampleLabel:'使用场景',setup:'开始前需要准备',steps:'三步开始使用',stepOne:'登录并创建',stepTwo:'配置并测试',stepThree:'接入结果或公开 URL',compareTitle:'与同类服务的差异',pico:'PicoSvc 的侧重点',other:'其他服务官方文档所述',source:'阅读官方资料',caveat:'使用限制',plans:'代码中配置的套餐及配额',perService:'按服务计的月费；购买前请以结账页面的价格和条款为准。',question1:'不登录能看到什么？',answer1:'本指南、公布的配额和比较资料均无需登录。创建、编辑、执行资源和查看用量需要登录。',question2:'如何开始？',question3:'是否保证生产环境可用？',answer3:'否。这里介绍的是仓库代码所支持的功能，并非已经通过外部服务的生产验收。请在实际环境验证连接、输出和配额。',disclaimer:'本比较只介绍功能范围，不构成价格、性能、稳定性或整体优劣评判。请以链接中的官方文档为准。',documentation:'API 使用指南',workspace:'工作台',free:'Free',picoPlan:'Pico',plus:'PicoPlus' },
} as const;

export default function ProductLanding({ service, locale }: { service: Slug; locale: Locale }) {
  const copy = UI[locale];
  const profile = PRODUCT_OVERVIEW[service];
  const scenarios = SCENARIOS[service];
  const info = SERVICE_INFO[service];
  const lang = locale === 'zh-CN' ? 'zh-cn' : locale;
  const quota = PICOSVC_QUOTAS.find(item => item.service === info.name);
  const base = `/${lang}`;
  return <div className="productLanding" id="product-guide">
    <nav className="productLandingNav shell" aria-label={copy.guide}>
      <a className="productLandingBrand" href={`${base}/`}><span className="productLandingLogo" aria-hidden="true"/>PicoSvc</a>
      <div className="productLandingNavLinks"><a href={`${base}/`}>{copy.products}</a><a href="#product-use-cases">{copy.scenarios}</a><a href="#product-comparison">{copy.compare}</a><a href={`${base}/pricing/`}>{copy.pricing}</a><a className="productLandingNavTry" href="#workspace">{copy.workspace} ↓</a></div>
    </nav>
    <div className="shell productLandingContent">
      <header className="productLandingHero"><div className="productLandingIcon" aria-hidden="true" style={{backgroundImage:`url('/icons/${service}.svg')`}}/><div className="productLandingHeroText"><span className="productLandingEyebrow">PICOSVC / {info.name.toUpperCase()} · {copy.guide}</span><h1>{info.name} — {copy.hero}</h1><p>{profile.purpose[locale]}</p><p className="productLandingSubline">{copy.tagline}</p><div className="productLandingCtas"><a className="productLandingPrimary" href="#workspace">{copy.try} ↓</a><a href={`${base}/pricing/`}>{copy.viewPricing} ↗</a></div></div></header>
      <div className="productLandingJump" aria-label={copy.guide}><a href="#product-features">{copy.explore} ↓</a><a href="#product-use-cases">{copy.scenarios} ↓</a><a href="#product-comparison">{copy.compare} ↓</a><a href="#product-faq">{copy.faq} ↓</a></div>
      <section id="product-features" className="productLandingSection" aria-labelledby="product-features-title"><div className="productLandingSectionHead"><span>01 / FEATURES</span><h2 id="product-features-title">{copy.overview}</h2></div><div className="productLandingFeatureGrid"><article><span>01</span><p>{profile.purpose[locale]}</p></article><article><span>02</span><p>{profile.example[locale]}</p></article><article><span>03</span><p>{profile.approach[locale]}</p></article></div></section>
      <section id="product-use-cases" className="productLandingSection" aria-labelledby="product-use-cases-title"><div className="productLandingSectionHead"><span>02 / USE CASES</span><h2 id="product-use-cases-title">{copy.examples}</h2></div><div className="productLandingCases">{scenarios.uses.map((useCase, index) => <article key={index}><span>{copy.exampleLabel} {String(index + 1).padStart(2,'0')}</span><p>{useCase[locale]}</p></article>)}</div><aside className="productLandingSetup"><strong>{copy.setup}</strong><p>{scenarios.setup[locale]}</p></aside></section>
      <section className="productLandingSection" aria-labelledby="product-steps-title"><div className="productLandingSectionHead"><span>03 / QUICK START</span><h2 id="product-steps-title">{copy.steps}</h2></div><ol className="productLandingSteps"><li><strong>{copy.stepOne}</strong><p>{scenarios.setup[locale]}</p></li><li><strong>{copy.stepTwo}</strong><p>{profile.example[locale]}</p></li><li><strong>{copy.stepThree}</strong><p>{profile.approach[locale]}</p></li></ol></section>
      {quota && <section className="productLandingSection" aria-labelledby="product-pricing-title"><div className="productLandingSectionHead"><span>04 / PLANS</span><h2 id="product-pricing-title">{copy.plans}</h2></div><div className="productLandingPlans"><article><strong>{copy.free}</strong><span>$0</span><p>{quota.free}</p></article><article><strong>{copy.picoPlan}</strong><span>${PICOSVC_PRICING.standalone.pico} / mo</span><p>{quota.pico}</p></article><article><strong>{copy.plus}</strong><span>${PICOSVC_PRICING.standalone.picoPlus} / mo</span><p>{quota.picoPlus}</p></article></div><p className="productLandingFootnote">{copy.perService}</p></section>}
      <section id="product-comparison" className="productLandingSection" aria-labelledby="product-comparison-title"><div className="productLandingSectionHead"><span>05 / ALTERNATIVES</span><h2 id="product-comparison-title">{copy.compareTitle}</h2></div><div className="productLandingCompare"><article><span>PICOSVC / {info.name.toUpperCase()}</span><h3>{copy.pico}</h3><p>{profile.approach[locale]}</p></article><article><span>{profile.alternative.name}</span><h3>{copy.other}</h3><p>{profile.alternative.scope[locale]}</p><a href={profile.alternative.url} target="_blank" rel="noopener noreferrer">{copy.source}: {profile.alternative.name} ↗</a></article></div><aside className="productLandingBoundary"><strong>{copy.caveat}</strong><p>{profile.boundary[locale]}</p></aside><p className="productLandingFootnote">{copy.disclaimer}</p></section>
      <section id="product-faq" className="productLandingSection" aria-labelledby="product-faq-title"><div className="productLandingSectionHead"><span>06 / FAQ</span><h2 id="product-faq-title">{copy.faq}</h2></div><div className="productLandingFaq"><details><summary>{copy.question1}</summary><p>{copy.answer1}</p></details><details><summary>{copy.question2}</summary><p>{scenarios.setup[locale]} {profile.example[locale]}</p></details><details><summary>{copy.question3}</summary><p>{copy.answer3}</p></details></div></section>
      <footer className="productLandingEnd"><a className="productLandingPrimary" href="#workspace">{copy.try} ↓</a><a href="https://github.com/YAMA-TANA/remote-mcp-factory/blob/main/docs/PICOSVC_API_GUIDE.md" target="_blank" rel="noopener noreferrer">{copy.documentation} ↗</a><a href={`${base}/pricing/`}>{copy.pricing} ↗</a></footer>
    </div>
  </div>;
}
