export type JsonLang = 'ja' | 'en' | 'zh-CN';
export const JSON_COPY: Record<JsonLang, Record<string, string>> = {
  ja: {
    title: 'JSONストア管理', intro: 'ドキュメントとアクセス権限を管理します。', endpoint: '公開APIのベースURL', endpointHint: '末尾にキーを追加してGET・PUT・DELETE。トークンはURLに含めないでください。', copy: 'コピー', close: '閉じる', loading: '処理中…', refresh: '更新', settings: '読み取り権限', publicRead: 'トークンなしのGETを許可', publicHint: '公開するとURLを知る人は全ドキュメントを読めます。書き込みにはトークンが必要です。', publicConfirm: 'このストアの全ドキュメントの公開読み取りを許可しますか？', privateConfirm: '公開読み取りを停止しますか？', saveSettings: '公開設定を保存', settingsSaved: '公開設定を更新しました。', document: 'ドキュメント', documentHint: '保存すると同じキーの内容を上書きします。', key: 'ドキュメントキー', value: 'JSONの内容', read: '読み込み', save: '保存', remove: '削除', docLoaded: 'ドキュメントを読み込みました。', docSaved: '保存しました。', docDeleted: '削除しました。', overwrite: 'このキーの最新内容を読み込んでいません。上書きする可能性があります。続けますか？', deleteConfirm: 'このドキュメントを完全に削除しますか？', invalidKey: 'キーは1〜200文字の英数字と . _ : @ / - のみ使用できます。', invalidValue: '256 KiB以内の正しいJSONを入力してください。nullも保存できます。', tokens: '権限付きトークン', tokenHint: '発行時のみ表示されます。1ストアにつき最大20個です。', tokenLabel: 'ラベル', scope: '権限', readScope: '読み取りのみ', writeScope: '書き込みのみ', bothScope: '読み書き', prefix: '許可するキープレフィックス（空欄なら全キー）', expires: '有効期限（任意・ローカル日時）', issue: '発行', issued: 'トークンを発行しました。', tokenList: '発行済みトークン', empty: 'まだありません。', revoke: '無効化', revokeConfirm: 'このトークンを無効化しますか？', revoked: 'トークンを無効化しました。', root: 'マスタートークン', rotate: 'マスタートークンを再発行', rotateConfirm: '現在のマスタートークンは即時無効になります。権限付きトークンは維持されます。続けますか？', rotated: 'マスタートークンを再発行しました。', oneTime: '今回限り表示されるトークン', oneTimeHint: '離れると再取得できません。安全に保管してください。', reveal: '表示', hide: '隠す', clear: '表示を消去', discard: '表示中のトークンは再取得できません。破棄して続けますか？', export: 'ドキュメントのエクスポート', exportHint: 'キー順で最大100件・約1 MiBを1ページずつ取得します。全件一括ではありません。', loadPage: '最初のページ', next: '次のページ', download: '表示中のページをJSON保存', page: 'このページの件数', finished: '続きはありません。', storeDelete: 'ストアを完全に削除', storeDeleteConfirm: 'ストア・全ドキュメント・トークンを完全に削除しますか？', failed: '処理に失敗しました。', tokenInvalid: 'プレフィックス・期限・ラベルを確認してください。', tokenNoResponse: 'APIから発行済みトークンを取得できませんでした。', invalidResponse: 'APIの応答形式が正しくありません。'
  },
  en: {
    title: 'JSON store management', intro: 'Manage documents and access rights.', endpoint: 'Public API base URL', endpointHint: 'Append a key to GET, PUT or DELETE a document. Never put tokens in URLs.', copy: 'Copy', close: 'Close', loading: 'Working…', refresh: 'Refresh', settings: 'Read access', publicRead: 'Allow GET without a token', publicHint: 'Anyone with the URL can read all documents when enabled. Writes still require a token.', publicConfirm: 'Enable unauthenticated reading of every document in this store?', privateConfirm: 'Disable public reading?', saveSettings: 'Save access settings', settingsSaved: 'Access settings updated.', document: 'Document', documentHint: 'Saving replaces the contents of this key.', key: 'Document key', value: 'JSON value', read: 'Read', save: 'Save', remove: 'Delete', docLoaded: 'Document loaded.', docSaved: 'Document saved.', docDeleted: 'Document deleted.', overwrite: 'You have not loaded the latest value for this key. Saving may overwrite an existing document. Continue?', deleteConfirm: 'Permanently delete this document?', invalidKey: 'Key must be 1–200 letters, numbers or . _ : @ / -.', invalidValue: 'Enter valid JSON up to 256 KiB; null is supported.', tokens: 'Scoped tokens', tokenHint: 'Tokens are shown only at issuance; up to 20 per store.', tokenLabel: 'Label', scope: 'Scope', readScope: 'Read only', writeScope: 'Write only', bothScope: 'Read and write', prefix: 'Allowed key prefix (blank = all keys)', expires: 'Expiration (optional, local time)', issue: 'Issue token', issued: 'Token issued.', tokenList: 'Issued tokens', empty: 'Nothing here yet.', revoke: 'Revoke', revokeConfirm: 'Revoke this token? Its clients will lose access.', revoked: 'Token revoked.', root: 'Master token', rotate: 'Rotate master token', rotateConfirm: 'The current master token will be invalidated immediately. Scoped tokens stay active. Continue?', rotated: 'Master token rotated.', oneTime: 'One-time token', oneTimeHint: 'It cannot be retrieved after leaving. Store it securely.', reveal: 'Reveal', hide: 'Hide', clear: 'Clear', discard: 'The displayed token cannot be retrieved again. Discard it and continue?', export: 'Export documents', exportHint: 'Fetch up to 100 key-ordered documents / about 1 MiB per page; this is not a full-store automatic export.', loadPage: 'First page', next: 'Next page', download: 'Download displayed page as JSON', page: 'Documents on this page', finished: 'No more pages.', storeDelete: 'Permanently delete store', storeDeleteConfirm: 'Permanently delete this store, its documents and tokens?', failed: 'Operation failed.', tokenInvalid: 'Check prefix, expiration and label.', tokenNoResponse: 'The API did not return the issued token.', invalidResponse: 'Invalid API response.'
  },
  'zh-CN': {
    title: 'JSON 存储管理', intro: '管理文档和访问权限。', endpoint: '公开 API 基础 URL', endpointHint: '在URL末尾追加键以GET、PUT或DELETE。请勿将令牌放入URL。', copy: '复制', close: '关闭', loading: '处理中…', refresh: '刷新', settings: '读取权限', publicRead: '允许无令牌GET', publicHint: '启用后任何知道URL的人都能读取全部文档；写入仍需令牌。', publicConfirm: '允许任何人无令牌读取全部文档？', privateConfirm: '关闭公开读取？', saveSettings: '保存权限', settingsSaved: '权限已更新。', document: '文档', documentHint: '保存会覆盖同名键的内容。', key: '文档键', value: 'JSON内容', read: '读取', save: '保存', remove: '删除', docLoaded: '已读取文档。', docSaved: '已保存。', docDeleted: '已删除。', overwrite: '尚未读取该键的最新内容，保存可能覆盖现有文档。继续？', deleteConfirm: '永久删除此文档？', invalidKey: '键长度为1至200，只能使用英数字及 . _ : @ / -。', invalidValue: '请输入不超过256 KiB的有效JSON；支持null。', tokens: '限定权限令牌', tokenHint: '仅在发行时显示，每存储最多20个。', tokenLabel: '标签', scope: '权限', readScope: '只读', writeScope: '只写', bothScope: '读写', prefix: '允许的键前缀（空白表示全部）', expires: '过期时间（可选，本地时间）', issue: '发行令牌', issued: '令牌已发行。', tokenList: '已发行令牌', empty: '暂无内容。', revoke: '撤销', revokeConfirm: '撤销此令牌？使用者将失去访问权限。', revoked: '令牌已撤销。', root: '主令牌', rotate: '轮换主令牌', rotateConfirm: '现有主令牌将立即失效，限定权限令牌不受影响。继续？', rotated: '主令牌已轮换。', oneTime: '仅本次显示的令牌', oneTimeHint: '离开后无法再次获取，请妥善保存。', reveal: '显示', hide: '隐藏', clear: '清除', discard: '显示中的令牌无法再次获取。清除并继续？', export: '导出文档', exportHint: '每页按键顺序读取最多100条、约1 MiB数据；不会自动导出全部。', loadPage: '第一页', next: '下一页', download: '下载当前页JSON', page: '当前页文档数', finished: '没有更多页。', storeDelete: '永久删除存储', storeDeleteConfirm: '永久删除存储、全部文档和令牌？', failed: '操作失败。', tokenInvalid: '请检查前缀、过期时间和标签。', tokenNoResponse: 'API未返回新令牌。', invalidResponse: 'API响应格式无效。'
  }
};
